### ISSUE TITLE
possible gam trend function

### ISSUE THREAD

**Issue by tmeeha** [AdamCSmithCWS/CBC_Spatial_Modeling#2]
Hey Adam. I added a simple R script to the repo called gam_trend_test.R. The script generates data and defines and tests a function for generating an annual trend (t, percent per year) and accumulated change (chg, percent over years) estimate from a sample of abundance indices. I am working it into your trends_function() which gets index samples from your index_function().

The function uses years (x) and index samples (y) as inputs. It fits a p-spline (like GAMYE?) to the full time series (1966-2019). The number of knots is total number of years divided by 4 (like GAMYE?). The index samples are on the log abundance scale so I am using a Gaussian error distribution. Then I generate annual percent change estimates based on chosen start and end years and fitted gam endpoints. Then derive accumulated change using chosen start and end years and t. Do this for a bunch of samples and get posteriors for t and chg, right?

Does this seem like a good general approach to getting trend and change estimates from posterior samples of indices?

**Comment by AdamCSmithCWS** [comment]
Hi Tim. Cool. YEs basically this is what I was thinking. I've also done a bit of fiddling with this in bbsBayes2 v1.1.2. So here's some more detail on what I did there. 

The default basis in the the GAMs in bbsBayes2 is "tp", the thin-plate splines that are also the default for `mgcv::s()`. 
Setting the upper bound on the knots is an interesting question. I wonder what makes the most sense. The n-years/4 that you've suggested makes a lot of sense (forces the smooth track variation that is >1-2 year fluctuations). I think for most "trend" assessments this makes sense (most interpret "trend" as something that happens over a 5 or more years, I think). Could also be something that we allow users to choose. 

I've implemented an initial take on this in the most recent bbsBayes2. I realised while doing it that it might make a lot of sense to separate the smooth generation for each posterior draw from the trend estimates. In bbsBayes2, I've added a function to generate the smoothed trajectories into the [`generate_indices()` function](https://github.com/bbsBayes/bbsBayes2/blob/3c53b41f789989bc777a2b45e98d39596997c821/R/generate-indices.R#L56C1-L61C58).  
I thought it might make sense to separate them because:
1. it takes a while to generate the smooths, so I wanted to only ever do it once.
2. The ends of smooths tend to be the most variable parts and so it will "always" (I think) make sense to smooth the entire trajectory and then draw trends from whatever time-window is desired from the entire time-series smooths. 

In there, you'll see that it generates a [smooth for each posterior draw of the full trajectory of indices](https://github.com/bbsBayes/bbsBayes2/blob/3c53b41f789989bc777a2b45e98d39596997c821/R/generate-indices.R#L378C3-L389C1), storing them as a[ matrix with the identical structure to the full indices](https://github.com/bbsBayes/bbsBayes2/blob/3c53b41f789989bc777a2b45e98d39596997c821/R/generate-indices.R#L380).

You'll also see that I kept the [draw-wise gam calculation very simple](https://github.com/bbsBayes/bbsBayes2/blob/3c53b41f789989bc777a2b45e98d39596997c821/R/generate-indices.R#L464C1-L470C2), but I you are right and it should more explicitly include which basis expansion and the number of knots as you did.

This matrix of posterior draws of the smooth trajectories is then [included in the function output](https://github.com/bbsBayes/bbsBayes2/blob/3c53b41f789989bc777a2b45e98d39596997c821/R/generate-indices.R#L400) - essentially a new set of indices on which end-point trends can be calculated.

In the `generate_trends()` function the user can tell it to[ base all trend calculations on the smooths](https://github.com/bbsBayes/bbsBayes2/blob/3c53b41f789989bc777a2b45e98d39596997c821/R/generate-indices.R#L400) and [here](https://github.com/bbsBayes/bbsBayes2/blob/3c53b41f789989bc777a2b45e98d39596997c821/R/generate-trends.R#L171C1-L182C4) if they have been added to the output from `generate_indices()`. The trends are [calculated the same way you have here](https://github.com/bbsBayes/bbsBayes2/blob/3c53b41f789989bc777a2b45e98d39596997c821/R/generate-trends.R#L171C1-L182C4), plus the other set of metrics (%-change, probability of change > x, etc) can also be calculated based on these smooths.
